from __future__ import annotations

import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROBLEMS_DIR = ROOT / "problems"
BUILD_DIR = ROOT / ".build"
WRAPPERS_DIR = BUILD_DIR / "wrappers"
ASSETS_DIR = BUILD_DIR / "assets"
GENERATED_PROBLEMS_TEX = ROOT / "generated-problems.tex"
MAIN_TEX = ROOT / "main.tex"
MAIN_PDF = ROOT / "main.pdf"

TITLE_RE = re.compile(r"\\begin\{problem\}\{([^}]*)\}")
WRAPPER_TEMPLATE = None


@dataclass(frozen=True)
class ProblemStatement:
    slug: str
    title: str
    letter: str
    statement_tex: Path
    wrapper_tex: Path



def require_problems_dir() -> None:
    if not PROBLEMS_DIR.is_dir():
        raise SystemExit(f"missing problems directory: {PROBLEMS_DIR}")



def discover_problem_dirs() -> list[Path]:
    return sorted(path for path in PROBLEMS_DIR.iterdir() if path.is_dir())



def statement_path_for(problem_dir: Path) -> Path:
    statement_tex = problem_dir / "statements" / "chinese" / "problem.tex"
    if not statement_tex.is_file():
        raise FileNotFoundError(f"missing chinese statement tex: {statement_tex}")
    return statement_tex



def extract_title(statement_tex: Path) -> str:
    text = statement_tex.read_text(encoding="utf-8")
    match = TITLE_RE.search(text)
    if not match:
        raise ValueError(f"cannot extract title from: {statement_tex}")
    return match.group(1).strip()



def problem_letter(index: int) -> str:
    if index < 0:
        raise ValueError("index must be non-negative")

    label = ""
    value = index
    while True:
        value, remainder = divmod(value, 26)
        label = chr(ord("A") + remainder) + label
        if value == 0:
            return label
        value -= 1



def to_posix(path: Path) -> str:
    return path.as_posix()



def make_wrapper(problem_dir: Path, statement_tex: Path) -> Path:
    relative_statement = statement_tex.relative_to(ROOT)
    wrapper_path = WRAPPERS_DIR / f"{problem_dir.name}.tex"
    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    asset_dir = ASSETS_DIR / problem_dir.name
    relative_asset_dir = asset_dir.relative_to(ROOT)
    asset_part = "{" + to_posix(relative_asset_dir) + "/}"
    statement_dir_part = "{" + to_posix(relative_statement.parent) + "/}"
    wrapper_content = "\n".join(
        [
            r"\begingroup",
            "\\graphicspath{" + asset_part + statement_dir_part + "}",
            rf"\input{{{to_posix(relative_statement)}}}",
            r"\endgroup",
            "",
        ]
    )
    wrapper_path.write_text(wrapper_content, encoding="utf-8")
    return wrapper_path



def collect_problems() -> list[ProblemStatement]:
    problems: list[ProblemStatement] = []
    for index, problem_dir in enumerate(discover_problem_dirs()):
        statement_tex = statement_path_for(problem_dir)
        wrapper_tex = make_wrapper(problem_dir, statement_tex)
        problems.append(
            ProblemStatement(
                slug=problem_dir.name,
                title=extract_title(statement_tex),
                letter=problem_letter(index),
                statement_tex=statement_tex,
                wrapper_tex=wrapper_tex,
            )
        )
    return problems



def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\\textbackslash{}",
        "&": r"\\&",
        "%": r"\\%",
        "$": r"\\$",
        "#": r"\\#",
        "_": r"\\_",
        "{": r"\\{",
        "}": r"\\}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)



def render_generated_tex(problems: list[ProblemStatement]) -> str:
    lines: list[str] = [
        "% Auto-generated by build.py",
        r"\RenderContestTitlePage{%",
        r"\begin{table}[!htp]",
        r"\centering",
        r"\setlength{\tabcolsep}{10pt}",
        r"\begin{tabular}{|p{1cm}|p{10cm}|}",
        r"\hline",
        r"\centering\arraybackslash 题号 & \centering\arraybackslash 题目名称 \\",
        r"\hline",
    ]
    for problem in problems:
        lines.append(
            rf"\centering\arraybackslash {problem.letter} & \centering\arraybackslash {latex_escape(problem.title)} \\\\"
        )
    lines.extend(
        [
            r"\hline",
            r"\end{tabular}",
            r"\end{table}",
            r"}",
            "",
        ]
    )
    for problem in problems:
        relative_wrapper = problem.wrapper_tex.relative_to(ROOT)
        lines.append(rf"\input{{{to_posix(relative_wrapper)}}}")
        lines.append("")
    return "\n".join(lines)



def write_generated_tex(problems: list[ProblemStatement]) -> None:
    GENERATED_PROBLEMS_TEX.write_text(render_generated_tex(problems), encoding="utf-8")



def copy_assets_for_problem(problem: ProblemStatement) -> None:
    source_dir = problem.statement_tex.parent
    target_dir = ASSETS_DIR / problem.slug
    target_dir.mkdir(parents=True, exist_ok=True)
    candidate_dirs = [source_dir]
    statement_sections_dir = source_dir.parent.parent / "statement-sections" / source_dir.name
    if statement_sections_dir.is_dir():
        candidate_dirs.append(statement_sections_dir)
    for directory in candidate_dirs:
        for source in directory.iterdir():
            if source.is_file():
                shutil.copy2(source, target_dir / source.name)



def prepare_build_dir(problems: list[ProblemStatement]) -> None:
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    WRAPPERS_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    for problem in problems:
        copy_assets_for_problem(problem)
        make_wrapper(PROBLEMS_DIR / problem.slug, problem.statement_tex)



def run_xelatex() -> None:
    command = [
        "xelatex",
        "-interaction=nonstopmode",
        "-halt-on-error",
        MAIN_TEX.name,
    ]
    for _ in range(2):
        subprocess.run(command, cwd=ROOT, check=True)



def main() -> None:
    require_problems_dir()
    problems = collect_problems()
    if not problems:
        raise SystemExit("no problem directories found under problems/")
    prepare_build_dir(problems)
    write_generated_tex(problems)
    run_xelatex()
    print(f"Built {MAIN_PDF}")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"build failed with exit code {exc.returncode}", file=sys.stderr)
        raise
